# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'A:\proj\autoreply\autoreply\\src\acc_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_account_settings(object):
    def setupUi(self, account_settings):
        account_settings.setObjectName("account_settings")
        account_settings.resize(391, 300)
        self.proxy_box = QtWidgets.QGroupBox(account_settings)
        self.proxy_box.setGeometry(QtCore.QRect(10, 120, 371, 51))
        self.proxy_box.setObjectName("proxy_box")
        self.proxy_info_label = QtWidgets.QLabel(self.proxy_box)
        self.proxy_info_label.setGeometry(QtCore.QRect(10, 20, 351, 16))
        self.proxy_info_label.setObjectName("proxy_info_label")
        self.autoreply_box = QtWidgets.QGroupBox(account_settings)
        self.autoreply_box.setGeometry(QtCore.QRect(10, 10, 371, 101))
        self.autoreply_box.setObjectName("autoreply_box")
        self.status_label = QtWidgets.QLabel(self.autoreply_box)
        self.status_label.setGeometry(QtCore.QRect(10, 40, 351, 20))
        self.status_label.setObjectName("status_label")
        self.is_active_cb = QtWidgets.QCheckBox(self.autoreply_box)
        self.is_active_cb.setGeometry(QtCore.QRect(10, 20, 351, 17))
        self.is_active_cb.setObjectName("is_active_cb")
        self.logout_button = QtWidgets.QPushButton(self.autoreply_box)
        self.logout_button.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.logout_button.setObjectName("logout_button")

        self.retranslateUi(account_settings)
        QtCore.QMetaObject.connectSlotsByName(account_settings)

    def retranslateUi(self, account_settings):
        _translate = QtCore.QCoreApplication.translate
        account_settings.setWindowTitle(_translate("account_settings", "Account settings"))
        self.proxy_box.setTitle(_translate("account_settings", "Proxy"))
        self.proxy_info_label.setText(_translate("account_settings", "Proxy isn\'t used"))
        self.autoreply_box.setTitle(_translate("account_settings", "Autoreply"))
        self.status_label.setText(_translate("account_settings", "Status:"))
        self.is_active_cb.setText(_translate("account_settings", "Active"))
        self.logout_button.setText(_translate("account_settings", "Exit"))
